# Generated by Django 5.0 on 2026-03-08 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('accessories', 'Accessories'), ('cables', 'Cables'), ('consumables', 'Consumables'), ('software', 'Software'), ('parts', 'Parts'), ('other', 'Other')], default='other', max_length=20)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('quantity_in_stock', models.PositiveIntegerField(default=0)),
                ('minimum_stock_level', models.PositiveIntegerField(default=5)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('supplier', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Inventory',
                'ordering': ['name'],
            },
        ),
    ]
